server:
  port: 8443 #服务端口
#spring相关配置
spring:
  application:
    name: Hu-sever #服务名
  datasource:
    driver-class-name: oracle.jdbc.driver.OracleDriver  #数据库驱动包
    url: jdbc:oracle:thin:@localhost:1521:orcl
    username: C##huyuxin
    password: huyuxin
    max-idle: 10
    max-wait: 10000
    min-idle: 5
    initial-size: 5

swagger:
  flag: true

mybatis:
  type-aliases-package: com.entity
  mapper-locations: mapper/*.xml
